# Generated by Django 4.2 on 2023-04-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orlando_pizzas', '0003_pizza_date_added_toppings_date_added_toppings_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='text',
        ),
    ]
