# Generated by Django 4.2 on 2023-04-16 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orlando_pizzas', '0004_remove_toppings_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='date_added',
        ),
        migrations.AddField(
            model_name='toppings',
            name='toppping_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
