# Generated by Django 4.2 on 2023-04-21 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orlando_pizzas', '0006_toppings_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toppings',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='toppping_name',
            field=models.CharField(default='Default', max_length=25),
        ),
    ]
