# Generated by Django 4.2 on 2023-04-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orlando_pizzas', '0007_toppings_text_alter_toppings_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
